# -*- coding: utf-8 -*-
# vim: ft=yaml
---
prometheus:
  div: '/'
  force: false
  overwrite: true
  extra_files: {}
  wanted:
    clientlibs: []
    component:
      - prometheus
      - alertmanager
      - node_exporter
      # memcached_exporter    # only available as archive
    firewall: false           # disabled for travis ci
  dir:
    default: /etc/default
    archive: /opt/prometheus
    etc: /etc/prometheus
    service: /usr/lib/systemd/system
    symlink: /usr/local
    tmp: /tmp/prometheus
    var: /var/lib/prometheus

  pkg:
    uri: https://github.com/prometheus
    use_upstream_repo: false
    use_upstream_package: true
    use_upstream_archive: false
    deps:
      - gzip
      - tar
    repo:
      humanname: prometheus
      name: prometheus
      comments:
        - installed by salt
      enabled: 1
      gpgcheck: 1

    component:
      alertmanager:
        version: v0.21.0
        config_file: /etc/prometheus/alertmanager.yml
        config: {}
        environ_file: /etc/default/prometheus-alertmanager
        environ:
          environ_arg_name: ARGS
        # These service args will not impact installs using the non archive method and
        # instead should be added as environ args in such a case
        service:
          args:
            config.file: /etc/prometheus/alertmanager.yml
            storage.path: /var/lib/alertmanager
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9093
            # tcp/9094
        archive:
          source_hash: 9ccd863937436fd6bfe650e22521a7f2e6a727540988eef515dde208f9aef232
        commands:
          - amtool
          - alertmanager
      blackbox_exporter:
        version: v0.18.0
        config_file: /etc/prometheus/blackbox_exporter.yml
        config: {}
        environ_file: /etc/default/prometheus-blackbox-exporter
        environ:
          environ_arg_name: ARGS
        archive:
          source_hash: a87f9530e31e2b20d03a6d941f6f051c57ee724f24b38f2615b8580ca63966dc
        commands:
          - blackbox_exporter
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9110
      consul_exporter:
        version: v0.7.1
        archive:
          source_hash: 92ffd37fb5f2350df21e7a688c28e7bb2882c309f613400eafdc411c818ec048
        commands:
          - consul_exporter
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9107
      graphite_exporter:
        version: v0.9.0
        archive:
          source_hash: 8da5bf07180f345abbd0e3c5ddf0f2bd319d930b6f9dd0385f4cfebdc6815c86
        commands:
          - graphite_exporter
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9108
      haproxy_exporter:
        version: v0.11.0
        archive:
          source_hash: 525ec4684b33a7fd1b23fe39e5c378e09cbc52b56fb3e203cffa26e09d22d10d
        commands:
          - haproxy_exporter
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9101
      memcached_exporter:
        version: v0.7.0
        archive:
          source_hash: a8dec3f2493330159b02ab5f8916726d2d41d70170f23206b1987cdb450a839b
        commands:
          - memcached_exporter
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9150
      mysqld_exporter:
        version: v0.12.1
        archive:
          source_hash: 133b0c281e5c6f8a34076b69ade64ab6cac7298507d35b96808234c4aa26b351
        commands:
          - mysqld_exporter
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9207
      node_exporter:
        version: v1.0.1
        environ_file: /etc/default/prometheus-node-exporter
        environ:
          environ_arg_name: ARGS
        config_file: /etc/prometheus/node_exporter.yml
        config: {}
        # These service args will not impact installs using the non archive method and
        # instead should be added as environ args in such a case
        service:
          args:
            collector.textfile.directory: /var/tmp/node_exporter
        archive:
          source_hash: 3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae
        commands:
          - node_exporter
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9100
      prometheus:
        name: prometheus
        version: v2.22.1
        config_file: /etc/prometheus/prometheus.yml
        config: {}
        environ_file: /etc/default/prometheus
        environ:
          environ_arg_name: ARGS
        # These service args will not impact installs using the non archive method and
        # instead should be added as environ args in such a case
        service:
          args:
            config.file: /etc/prometheus/prometheus.yml
            storage.tsdb.path: /var/lib/prometheus/data
        commands:
          - prometheus
          - promtool
        archive:
          source_hash: 9001a9cb939e0a6d9f2b67d22506c620bc9457777272fced43274b032ba35f44
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9090
      pushgateway:
        version: v1.3.0
        environ_file: /etc/default/prometheus-pushgateway
        environ:
          environ_arg_name: ARGS
        config_file: /etc/prometheus/pushgateway.yml
        config: {}
        service: {}
        archive:
          source_hash: 1ea7260a41c710a5b0f8ca1b90d18e70afdcc98ce23de61f88aba79a73d85947
        commands:
          - pushgateway
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9091
      statsd_exporter:
        version: v0.18.0
        archive:
          source_hash: d06793bd984a67e5cbead82b74e0a0f7bcd2518914ba243ab63ff8e8da532ca5
        commands:
          - statsd_exporter
        firewall:
          ports:
            - tcp/4505
            - tcp/4506
            - tcp/9102
    clientlibs:
      # https://prometheus.io/docs/instrumenting/clientlibs
      # no bash & perl client tarballs are available
      golang:
        version: v1.6.0
        archive:
          uri: https://github.com/prometheus/client_golang/archive
          skip_verify: true
      java:
        version: vparent-0.9.0
        archive:
          uri: https://github.com/prometheus/client_java/archive
          skip_verify: true
      python:
        version: v0.7.1
        archive:
          uri: https://github.com/prometheus/client_python/archive
          skip_verify: true
      ruby:
        version: v2.0.0
        archive:
          uri: https://github.com/prometheus/client_ruby/archive
          skip_verify: true
      c:
        version: v0.1.1
        archive:
          uri: https://github.com/digitalocean/prometheus-client-c/archive
          skip_verify: true
      cpp:
        version: v0.9.0
        archive:
          uri: https://github.com/jupp0r/prometheus-cpp/archive
          skip_verify: true
      clisp:
        version: v0.4.1
        archive:
          uri: https://github.com/deadtrickster/prometheus.cl/archive
          skip_verify: true
      dart:
        version: v0.4.0+4
        archive:
          uri: https://github.com/tentaclelabs/prometheus_client/archive
          skip_verify: true
      elixir:
        version: v2.0.0
        archive:
          uri: https://github.com/deadtrickster/prometheus.ex/archive
          skip_verify: true
      erlang:
        version: v4.4.0
        archive:
          uri: https://github.com/deadtrickster/prometheus.erl/archive
          skip_verify: true
      haskell:
        version: prometheus-proc-0.1.2.0
        archive:
          uri: https://github.com/fimad/prometheus-haskell/archive
          skip_verify: true
      nginx-lua:
        version: v0.20200420
        archive:
          uri: https://github.com/knyar/nginx-lua-prometheus/archive
          skip_verify: true
      tarantool-lua:
        version: v1.0.4
        archive:
          uri: https://github.com/tarantool/prometheus/archive
          skip_verify: true
      net:
        version: v3.5.0
        archive:
          uri: https://github.com/prometheus-net/prometheus-net/archive
          skip_verify: true
      node:
        version: v12.0.0
        archive:
          uri: https://github.com/siimon/prom-client/archive
          skip_verify: true
      php:
        version: v1.0.2
        archive:
          uri: https://github.com/endclothing/prometheus_client_php/archive
          skip_verify: true
      r:
        version: v1.0.1
        archive:
          uri: https://github.com/cfmack/pRometheus/archive
          skip_verify: true
      rust:
        version: v0.8.0
        archive:
          uri: https://github.com/tikv/rust-prometheus/archive
          skip_verify: true

  # Just here for testing
  added_in_defaults: defaults_value
  winner: defaults

  identity:
    rootuser: root
    rootgroup: root

  retry_option:
    # https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states
    attempts: 3
    until: true
    interval: 60
    splay: 10
  linux:
    altpriority: 0
  kernel: linux
